### ISSUE TITLE
Manual control for login poup

### ISSUE THREAD

**Issue by onemoreprince** [surendhar153/one-tap-google-sign-in#6]
Currently, there is no option to set a custom trigger (link) or page where this login option can remain for access to those visitors who choose to close the pop up for the first time.

It would be great if we can show the login option on a permanent login page or can trigger the login popup form a button or menu item.

**Comment by surendhar153** [comment]
Currently one tap google sign-in sign-up is not a replacement for traditional login with google button.

And one tap only shows google accounts that are already logged in the browser. And if you need to use a different google account. You may need to use login with google account button.

Having several features in mind and one is to add a login with google button and a menu link to trigger normal google login popup. But it can't trigger a One Tap Widget

But for now users need to use other google login plugins available in the repository.

**Comment by surendhar153** [comment]
But will definitely work on the timeout for the login after the one tap widget is closed. But triggering the widget with a button will not be a better UX. And One Tap Widget won't work when third party cookies are blocked for example firefox is blocking third party cookies as a privacy protection. So as for now the One Tap Widget is not a replacement and only a better login alternative when it can be used.

**Comment by surendhar153** [comment]
Manual Trigger for the one tap widget won't be added. Look out for **Login with Google** button feature to trigger the normal google OAuth login in the future updates.
